using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace Peachpie.WordPress.Internal
{
    sealed class PeachpieWpPlugin : IWpPlugin
    {
        public static readonly PeachpieWpPlugin Instance = new PeachpieWpPlugin();

        private PeachpieWpPlugin() { }

        static string GetDashboardRightNow()
        {
            return string.Format(
                "<ul>" +
                "<li><img src='{0}' style='width:76px;margin:0 auto;display:block;'/></li>" +
                "<li>{1}</li>" +
                "</ul>",
                "https://raw.githubusercontent.com/peachpiecompiler/peachpie/master/docs/logos/round-orange-196x196.png",
                "<b>Hello from .NET!</b><br/>The site is powered by .NET Core instead of PHP, compiled entirely to MSIL bytecode using PeachPie.");
        }

        public void Configure(IWpApp app)
        {
            //
            // Dashboard:
            //

            // add information into Right Now section
            app.DashboardRightNow(GetDashboardRightNow);

            // do not allow editing of .php files:
            app.AddFilter("editable_extensions", new Func<IList, IList>(editable_extensions =>
            {
                editable_extensions.Remove("php");
                return editable_extensions;
            }));

            //
            // Blogs:
            //

            // alter generated by metadata
            // add analytics
        }
    }
}
